spring:
  application:
    name: license-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: db, micro
management:
  endpoints:
    web:
      base-path: "/"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true